name: 'Sync DAGs'

on:
  pull_request:
    branches:
      - master
      - main

  push:
    branches:
      - master
      - main

jobs:
  changes:
    name: 'Find changed DAGs'
    runs-on: ubuntu-latest
    outputs:
      elements: ${{ steps.changes.outputs.changes }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          # sync when pipeline was updated
          github_actions:
            - '.github/workflows/sync_dags.yml'

  deploy:
    name: Deploy DAGs
    runs-on: ubuntu-latest
    needs: changes    
    
    strategy:
      max-parallel: 1
      matrix:
        value: ${{ fromJson(needs.changes.outputs.elements) }}

    steps:
    - uses: actions/checkout@v2

    - name: print changes
      run: |
        echo "${{ matrix.value }}"

    - name: print all secrets
      shell: bash
      run: echo "$SECRETS_CONTEXT"
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}

    - name: print secrets
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_DAG_BUCKET_FOLDER: ${{ secrets.GCP_DAG_BUCKET_FOLDER }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_PROJECT_ID"
        echo "$GCP_DAG_BUCKET_FOLDER"
        echo "$GCP_SA_KEY"

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

#    - name: Deploy
#      run: |
#        echo "${{ secrets.GCP_DAG_BUCKET_FOLDER }}"
#        echo "${{ secrets.GCP_PROJECT_ID }}"

#GCP_SA_KEY
#GCP_PROJECT_ID
#GCP_DAG_BUCKET_FOLDER
#gsutil cp -r -n pipeline/opera/DAGs/ gs://${{ secrets.GCP_DAG_BUCKET_FOLDER }}/